system:
  actions:
   - action: streamon
     command: /home/octoprint/scripts/webcam start
     confirm: false
     name: Start video stream
   - action: streamoff
     command: /home/octoprint/scripts/webcam stop
     confirm: false
     name: Stop video stream
webcam:
  stream: http://container_address:8080/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/ffmpeg
  streamRatio: '4:3'
